FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY fog_node/ ./fog_node/

ENV BACKEND_URL=http://backend:5002/ingest
ENV FOG_PORT=5001

EXPOSE 5001

CMD ["python", "fog_node/fog_node.py"]
